Add missing field auto_close_items to Task, CreateTask, UpdateTask
lokalise/go-lokalise-api pull request #41
Opened 2022-12-19 07:17 UTC by sumanrana10048483

### Summary

`auto_close_items` field is there in official [documentation](https://developers.lokalise.com/reference/tasks-object) but Golang library don't have that field.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here.

2022-12-19 07:21 UTC, sumanrana10048483 commented
@andrewLab-lokalise Please review and merge this PR. I already raised this issue to Lokalise technical support team.

2023-01-04 10:14 UTC, yarlson approved these changes

2023-01-04 10:17 UTC, yarlson requested changes

2023-01-04 10:17 UTC, yarlson commented on svc_task.go
> +// noinspection GoUnusedConst
`go fmt` fails on this changes

2023-01-04 10:31 UTC, sumanrana10048483 commented on svc_task.go
> +// noinspection GoUnusedConst
This is fixed.

2023-01-04 10:39 UTC, yarlson commented
@sumanrana10048483 please, run `go fmt ./...`, and commit the changes

2023-01-04 10:46 UTC, sumanrana10048483 commented
> @sumanrana10048483 please, run `go fmt ./...`, and commit the changes

I ran this command. And I get this changes automatically https://github.com/lokalise/go-lokalise-api/pull/41/commits/ed781fa1a756940032783672193177d7bd89bbcb

2023-01-04 10:54 UTC, merged